name: code deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy Files to Server 
        uses: appleboy/scp-action@v0.2.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          Key: ${{ secrets.SERVER_KEY }}
          source: "./*"
          target: "~/azmi"

      - name: Run deployment commands on server
        run: |
          ssh -i ${{ secrets.SERVER_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/azmi
            npm install
            npm run build
          EOF
