name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.9'
      - name: Install dependencies and test
        run: |
          npm install
      
      - name: Set up SSH key for server deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_KEY }}
      
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@168.119.238.20 "cd ~/azmi && git pull && npm install && npm run build || { echo 'Deployment failed!'; exit 1; }"
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_KEY }}
