name: Code Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3                    

      - name: Run deployment commands on server
        run: |
          ssh -i ${{ secrets.SERVER_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            if command -v nvm > /dev/null 2>&1; then
              nvm use 16  # Example: Ensure Node.js version 16 is used
            fi
            cd ~/azmi
            npm install
            npm run build || { echo 'Deployment failed!'; exit 1; }
          EOF
