name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.9'
      - name: Install dependencies and test
        run: |
          npm install
      - name: Run deployment commands on server
          run: |
       ssh -i ${{ secrets.SERVER_KEY }} root@${{ secrets.SERVER_HOST }} << 'EOF'
         cd ~/azmi || { echo "Directory not found"; exit 1; }
         npm install || { echo "npm install failed"; exit 1; }
        npm run build || { echo "npm run build failed"; exit 1; }
          EOF
